### PR TITLE
Fix H563ZI clock config.

### LINKED ISSUE #2505: Incorrect clock settings for NUCLEO-H563ZI
When I used CubeMX to verify clock settings of NUCLEO-H563ZI, an error occurred.
I also looked at reference datasheet for H563ZI chip and found some parts that were not optimized.

- ADC/DAC input clock is too high
https://github.com/stm32duino/Arduino_Core_STM32/blob/6e60087cabd8a037169d0ed6df4edc1f2d457bd9/variants/STM32H5xx/H563Z(G-I)T_H573ZIT/variant_NUCLEO_H563ZI.cpp#L238

The maximum clock for ADC/DAC components is 125MHz, but HCLK is 250MHz, so input clock is too high.
As an idea, by setting PLL2 to `N = 125` `R = 4` it is possible to supply 125MHz from PLL2R to ADC/DAC.

- LPUART clock is low
https://github.com/stm32duino/Arduino_Core_STM32/blob/6e60087cabd8a037169d0ed6df4edc1f2d457bd9/variants/STM32H5xx/H563Z(G-I)T_H573ZIT/variant_NUCLEO_H563ZI.cpp#L237

The LPUART will accept up to 250MHz, but PLL2Q is set to 32MHz, which may result in reduced performance.
I think using a PCLK3 (250MHz) would be fine.

The H563ZI Generic board seems to have same problem.

https://github.com/stm32duino/Arduino_Core_STM32/blob/6e60087cabd8a037169d0ed6df4edc1f2d457bd9/variants/STM32H5xx/H563Z(G-I)T_H573ZIT/generic_clock.c#L81

### PR DESCRIPTION
**Pull request by dojyorin**
## Pull Request template

Please, Make sure that your PR is not a duplicate.
Search among the [Pull request](https://github.com/stm32duino/Arduino_Core_STM32/pulls) before creating one.

IMPORTANT: Please review the [CONTRIBUTING.md](https://github.com/stm32duino/Arduino_Core_STM32/blob/main/CONTRIBUTING.md) file for detailed contributing guidelines.

Thanks for submitting a pull request.
Please provide enough information so that others can review your pull request:

**Summary**

This PR fixes/implements the following **bugs/features**

* [x] ADC/DAC input clock is too high
* [x] LPUART clock is low
* [x] Optimize PLL ratio

- There were no plans to change LPUART, but since it will be lower than current value when I fix ADC/DAC problem, I changed it as described in #2505.
- By setting `SRC / M = 2` `N = 250` for PLL1/2/3 you can flexibly determine clock source frequency and easily calculate division P/Q/R.

e.g. Generic boards and NUCLEO-H563ZI are portable by simply changing value of PLLM.

<details>
<summary>CubeMX Screenshots</summary>

- for H563ZI
image

</details>

**Validation**

* Ensure CI build is passed.
* Demonstrate the code is solid. [e.g. Provide a sketch]

**Code formatting**

* Ensure AStyle check is passed thanks CI

**Closing issues**

Fixes #2505

### CODE REVIEW

File: variants/STM32H5xx/H563Z(G-I)T_H573ZIT/generic_clock.c [hunk 1]
```diff
@@ -77,11 +73,34 @@ WEAK void SystemClock_Config(void)
...
                                              | RCC_PERIPHCLK_OSPI | RCC_PERIPHCLK_SDMMC1
                                              | RCC_PERIPHCLK_USB;
-  PeriphClkInitStruct.AdcDacClockSelection = RCC_ADCDACCLKSOURCE_HCLK;
-  PeriphClkInitStruct.Lpuart1ClockSelection = RCC_LPUART1CLKSOURCE_HSI;
+  PeriphClkInitStruct.AdcDacClockSelection = RCC_ADCDACCLKSOURCE_PLL2R;
+  PeriphClkInitStruct.Lpuart1ClockSelection = RCC_LPUART1CLKSOURCE_PCLK3;
   PeriphClkInitStruct.OspiClockSelection = RCC_OSPICLKSOURCE_HCLK;
   PeriphClkInitStruct.Sdmmc1ClockSelection = RCC_SDMMC1CLKSOURCE_PLL1Q;
-  PeriphClkInitStruct.UsbClockSelection = RCC_USBCLKSOURCE_HSI48;
+  PeriphClkInitStruct.UsbClockSelection = RCC_USBCLKSOURCE_PLL3Q;
```
Comment (fpistm) [inline variants/STM32H5xx/H563Z(G-I)T_H573ZIT/generic_clock.c:80]: Not correct as USB clock is 50 MHz instead of 48 MHz.

File: variants/STM32H5xx/H563Z(G-I)T_H573ZIT/generic_clock.c [hunk 2]
```diff
@@ -77,11 +73,34 @@ WEAK void SystemClock_Config(void)
   PeriphClkInitStruct.PeriphClockSelection = RCC_PERIPHCLK_ADCDAC | RCC_PERIPHCLK_LPUART1
                                              | RCC_PERIPHCLK_OSPI | RCC_PERIPHCLK_SDMMC1
                                              | RCC_PERIPHCLK_USB;
-  PeriphClkInitStruct.AdcDacClockSelection = RCC_ADCDACCLKSOURCE_HCLK;
-  PeriphClkInitStruct.Lpuart1ClockSelection = RCC_LPUART1CLKSOURCE_HSI;
+  PeriphClkInitStruct.AdcDacClockSelection = RCC_ADCDACCLKSOURCE_PLL2R;
+  PeriphClkInitStruct.Lpuart1ClockSelection = RCC_LPUART1CLKSOURCE_PCLK3;
```
Comment (fpistm) [inline variants/STM32H5xx/H563Z(G-I)T_H573ZIT/generic_clock.c:77]: As stated, LPUART clock is intentionnaly set lo ower value to be able to use 9600 bauds.

**Review by fpistm — APPROVED** [review]
