### PR TITLE
Interrupts: remove C prototype and keep only C++ prototypes

### LINKED ISSUE #1601: Call of overloaded attachInterrupt is ambiguous with a lambda callback
When calling attachInterrupt with a lambda callback instead of a function I got the following error:
```c++
error: call of overloaded 'attachInterrupt(const uint8_t&, setup()::<lambda()>, int)' is ambiguous
   32 |     attachInterrupt(pin_trackpad_clock[0], [](){trackpad[0].int_on_clock();}, FALLING);
...
C:\Users\<user>\.platformio\packages\framework-arduinoststm32\cores\arduino/WInterrupts.h:28:8: note: candidate: 'void attachInterrupt(uint32_t, callback_function_t, uint32_t)'
   28 |   void attachInterrupt(uint32_t pin, callback_function_t callback, uint32_t mode);
      |        ^~~~~~~~~~~~~~~
C:\Users\<user>\.platformio\packages\framework-arduinoststm32\cores\arduino/WInterrupts.h:32:6: note: candidate: 'void attachInterrupt(uint32_t, void (*)(), uint32_t)'
   32 | void attachInterrupt(uint32_t pin, void (*callback)(void), uint32_t mode);
      |      ^~~~~~~~~~~~~~~
```
Header file WInterrupts.h indeed has 2 prototypes of this function and compiler can't decide which one to use with a lambda.
When the prototype with a function pointer (line 32) is removed, project compiles and works no matter attachInterrupt is called with a lambda or a function pointer.

Please note that Arduino version of attachInterrupt only has one prototype with a function pointer
and esp32 version has one prototype with std::function<void(void)>.

(Edit)
I am using default installation of PlatformIO in VS Code.
I have also tried the same concept with MSVC and MinGW with the same outcome.

### PR DESCRIPTION
**Pull request by ABOSTM**
**Summary**
Interrupts: remove C prototype and keep only C++ prototypes

attachInterrupt() C prototypes was not usable from C source file
(inheritance of former pure C implementation), and causes ambiguity
when used with lambda function as callback
Fixes #1601

### CODE REVIEW

File: cores/arduino/wiring.h [hunk 1]
```diff
@@ -47,6 +46,7 @@
   #include "WSerial.h"
   #include "WMath.h"
   #include "WString.h"
+  #include "WInterrupts.h"
```
Comment (fpistm) [inline cores/arduino/wiring.h:49]: Include are sorted by name

**Review by fpistm — CHANGES_REQUESTED** [review]

**Review by fpistm — APPROVED** [review]
