### PR TITLE
I2C Fix

### LINKED ISSUE #583: STM32 I2C driver "repeated start" issue
Hello,

I'm trying to connect to the MMA8451 accelerometer. This chip requires an I2C driver with repeated-start feature enabled to discuss with.
I've  a NUCLEO-F411RE, lib 1.6.1 and no repeated start is generated due to some low level limitations.
Let me explain: 
XferOptions variable is always set to `I2C_NO_OPTION_FRAME` in the `HAL_I2C_Transmit_IT`. So, once the Xfer is completed, it fires `I2C_MasterTransmit_TXE`. As the following condition is always false (stm32f4xx_hal_i2c.c):
`if ((CurrentXferOptions != I2C_FIRST_AND_LAST_FRAME) && (CurrentXferOptions != I2C_LAST_FRAME) && (CurrentXferOptions != I2C_NO_OPTION_FRAME))`
a STOP will be generated (line 5025):
```
      /* Disable EVT, BUF and ERR interrupt */
      __HAL_I2C_DISABLE_IT(hi2c, I2C_IT_EVT | I2C_IT_BUF | I2C_IT_ERR);

      /* Generate Stop */
      SET_BIT(hi2c->Instance->CR1, I2C_CR1_STOP);

```
Does someone can confirm ?
How could we override XferOptions by setting to `I2C_LAST_FRAME_NO_STOP` ?
Ok, I understand that it's not directly related to the framework by itself, but I observed that I2C driver is really different regarding the variant.
In other word, by using `TwoWire::endTransmission(false)`, it should not send a STOP condition (instead of UNUSED(endStop) ).

Thank you,
jean-marc

### PR DESCRIPTION
**Pull request by fpistm**
* Added the repeated-start feature in I2C driver (prviously done thanks #590).    
   Fixes #583
* Fix error management in Read/Write
   When NACK is received by master, instead of immediate re-transmission
   by twi driver, error is reported. Up to application to manage re-transmission.
* Review errors management to be aligned with Arduino [Wire.endTransmission()](https://www.arduino.cc/en/Reference/WireEndTransmission) API Reference:
  - 0:success
  - 1:data too long to fit in transmit buffer
  - 2:received NACK on transmit of address
  - 3:received NACK on transmit of data
  - 4:other error

### CODE REVIEW

File: cores/arduino/stm32/twi.c [hunk 1]
```diff
@@ -807,38 +806,36 @@ i2c_status_e i2c_slave_write_IT(i2c_t *obj, uint8_t *data, uint16_t size)
...
+        break;
       }
     }
-    /* When Acknowledge failure occurs (Slave don't acknowledge it's address)
-       Master restarts communication */
-  } while (((HAL_I2C_GetError(&(obj->handle)) & HAL_I2C_ERROR_AF) == HAL_I2C_ERROR_AF)
-           && (delta < I2C_TIMEOUT_TICK));
+
+    err = HAL_I2C_GetError(&(obj->handle));
+    if ((delta > I2C_TIMEOUT_TICK)
```
Comment (matthijskooijman) [inline cores/arduino/stm32/twi.c]: This introduces a new problem: When this timeout is triggered, I2C_OK is triggered. This happens because in the loop above, it checks for `(delta < I2C_TIMEOUT_TICK)`, so it breaks out of the loop as soon as `delta == I2C_TIMEOUT_TICK`. Then, this if checks for `(delta > I2C_TIMEOUT_TICK)`, which is not yet false. Since the hardware reports no errors either, `I2C_OK` is returned.

We noticed this when something confused the I2C hardware and prevented it from continuing somehow. We haven't figured out what the underlying cause is, but we did notice that we did not get an I2C error (just invalid data), which I think can be traced back to this problem.

The same applies to `i2c_write_master` above, I think.

Fixing this is, I think, a matter of replacing `>` with `>=` here.

Comment (matthijskooijman) [reply cores/arduino/stm32/twi.c]: One more thing: This `>` and `<` combination was already present in the old code, but due to the old structure there it would, I think, only be problematic when an ACK failure occured *exactly* a the timeout, which is of course extremely likely. These refactorings have caused this to happen on every timeout instead.

> Fixing this is, I think, a matter of replacing > with >= here.

We just tried this, and it seems to work. @hendrykaak is considering to prepare a PR for this.

Comment (fpistm) [reply cores/arduino/stm32/twi.c]: Right
